premier = 'https://www.flashscore.co/futbol/inglaterra/premier-league/resultados/'
ligue_1 = 'https://www.flashscore.co/futbol/francia/ligue-1/resultados/'
serie_a = 'https://www.flashscore.co/futbol/italia/serie-a/resultados/'
la_liga = 'https://www.flashscore.co/futbol/espana/laliga-ea-sports/resultados/'
bundes = 'https://www.flashscore.co/futbol/alemania/bundesliga/resultados/'
austria = 'https://www.flashscore.co/futbol/austria/bundesliga/resultados/'
bulgaria = 'https://www.flashscore.co/futbol/bulgaria/parva-liga/resultados/'
chipre = 'https://www.flashscore.co/futbol/chipre/cyta-championship/resultados/'
croacia = 'https://www.flashscore.co/futbol/croacia/hnl/resultados/'
dinamarca = 'https://www.flashscore.co/futbol/dinamarca/superliga/resultados/'
escocia = 'https://www.flashscore.co/futbol/escocia/premiership/resultados/'
gales = 'https://www.flashscore.co/futbol/gales/cymru-premier/resultados/'
grecia = 'https://www.flashscore.co/futbol/grecia/superliga/resultados/'
hungria = 'https://www.flashscore.co/futbol/hungria/otp-bank-liga/resultados/'
noruega = 'https://www.flashscore.co/futbol/noruega/eliteserien/resultados/'
israel = 'https://www.flashscore.co/futbol/israel/ligat-ha-al/resultados/'
holanda = 'https://www.flashscore.co/futbol/paises-bajos/eredivisie/resultados/'
polonia = 'https://www.flashscore.co/futbol/polonia/ekstraklasa/resultados/'
portugal = 'https://www.flashscore.co/futbol/portugal/liga-portugal/resultados/'
r_checa = 'https://www.flashscore.co/futbol/republica-checa/fortuna-liga/resultados/'
serbia = 'https://www.flashscore.co/futbol/serbia/super-liga/resultados/'
suiza = 'https://www.flashscore.co/futbol/suiza/super-league/resultados/'
turquia = 'https://www.flashscore.co/futbol/turquia/super-lig/resultados/'
ucrania = 'https://www.flashscore.co/futbol/ucrania/premier-league/resultados/'
belgica = 'https://www.flashscore.co/futbol/belgica/jupiler-pro-league/resultados/'
bosnia = 'https://www.flashscore.co/futbol/bosnia-y-herzegovina/premijer-liga-bih/resultados/'
brazil = 'https://www.flashscore.co/futbol/brasil/brasileirao-serie-a/resultados/'

dict_ligas = {
    'inglaterra' : premier,
    'francia' : ligue_1,
    'italia' : serie_a,
    'españa' : la_liga,
    'alemania' : bundes,
    'austria' : austria,
    'bulgaria' : bulgaria,
    'chipre' : chipre,
    'croacia' : croacia,
    'dinamarca' : dinamarca,
    'escocia' : escocia,
    'gales' : gales,
    'grecia' : grecia,
    'hungria' : hungria,
    'noruega' : noruega,
    'israel' : israel,
    'holanda' : holanda,
    'polonia' : polonia,
    'portugal' : portugal,
    'r_checa' : r_checa,
    'serbia' : serbia,
    'suiza' : suiza,
    'turquia' : turquia,
    'ucrania' : ucrania,
    'belgica' : belgica,
    'bosnia' : bosnia,
    'brazil' : brazil,
    }